### ISSUE TITLE
Add "response requested" to conference status

### ISSUE THREAD

**Issue by ablomeke** [fterbo/scotus-tools#12]
Seems like at least some of the "unknown" statuses are when the court requests a response from a respondent who has waived the right.

**Comment by fterbo** [comment]
I'm not sure what you mean by unknown statuses - do you have an example?  This seems like "pending" to me for the most part.  Even if we encoded the specific request for a response, that seems like something that should go in tags and not a status.

**Comment by fterbo** [comment]
Fixed in cb166b42a4a1dbb5d03e7d35a8c4e8d553d71f83
